config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/drllano1', status: 302)
  get 'drllano1', to: 'pages#profile', as: 'drllano1'
  get 'review', to: 'pages#review', as: 'review'
  get 'question', to: 'pages#question', as: 'question'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    respond_to do |format|
      format.html { render :about }
    end
  end
  def review
    respond_to do |format|
      format.html { render :review }
    end
  end
  def question
    answers = [
      "a) A class should have only one reason to change.",
      "b) Each developer on a team should have one main responsibility.",
      "c) Every app will have one responsibility that is most important to users."
    ]
    respond_to do |format|
      format.html { render :question, locals: { answers: answers }  }
    end
  end
end
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeworkProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/profile.html.erb
<h1>About Me!</h1>
<h2>By Alexis Orellano</h2>
<p>My intresets include</p>
 <ul>
   <li>Favorite Animal: Panda</li>
   <li>Hogwarts house: Hufflepuff</li>
   <li>Best astrology sign: Libra</li>
 </ul>
 <%= image_tag "panda.png", height: 300%>

<p><%= link_to 'Review', review_path %></p>

app/views/pages/question.html.erb
<h1>Practice Question</h1>
<p>Which of the following is the Single Responsibility Principle?</p>

<ul>
    <% answers.each do |a| %>
        <li><%= a %></li>
    <% end %>
</ul>

<p><%= link_to 'Question', question_path %></p>

app/views/pages/review.html.erb
<h1>Xcode</h1>
<h2>5/5</h2>
<%= image_tag "xcode.png", height: 500%>